// ─── Trash Talk Narratives ────────────────────────────────────────────────────
export const TRASH_TALK = [
  { emoji: '👑', owner: 'Daniyaal',        title: 'The Dynasty',               color: '#8b5cf6', body: `2x champion (2020 & 2023), +$330 all-time. In 2023 he went 13-3 with a 132.6 pts/wk average — the single most dominant season in league history. The rest of you are competing for 2nd place.` },
  { emoji: '🚽', owner: 'Nathan',          title: 'The Toilet Bowl Specialist', color: '#06b6d4', body: `2x Toilet Bowl loser (2020 & 2022), net +$5 all-time somehow. Nathan has mastered the art of being terrible. At least he's consistent? Runner-up in 2019 but has lived in the basement ever since.` },
  { emoji: '⚖️', owner: 'Armaan & Dustin', title: 'The 2022 Co-Champs (One Fell Far)', color: '#f59e0b', body: `The only shared championship in league history in 2022. Since then their paths diverged completely — Armaan made the 2023 championship game and won +$100 in 2024, while Dustin hit the 2024 toilet bowl at -$190 all-time. Same year, same trophy, very different endings.` },
  { emoji: '🎰', owner: 'Manu',            title: 'The Villain Arc',            color: '#ec4899', body: `Went 2-10 in his 2019 debut, then won the entire league in 2021. The ultimate villain arc. Also has the distinction of posting the league's lowest score ever in year 1. Currently -$80 net.` },
  { emoji: '📈', owner: 'Kerry',           title: 'The Redemption Arc',         color: '#d946ef', body: `Joined in 2022, scored the most points in league history, then crashed to last in 2023. Everyone wrote him off. Then he won the whole thing in 2025 for +$675 — the biggest single-year payout ever. Redemption arc complete.` },
  { emoji: '🎯', owner: 'Sonu',            title: 'The Full Circle',            color: '#ef4444', body: `Posted the league's highest single-game score in 2019. Multiple near-misses. Finally broke through to win the 2024 championship for +$600. Then immediately became the 2025 toilet bowl loser at -$125. That's a $725 swing in two seasons. Peak Sonu energy.` },
  { emoji: '🌅', owner: 'Raghav',          title: 'The Silent Threat',          color: '#22c55e', body: `2019 Champion — +$160 that year but -$260 net overall due to later buy-in increases. Quietly one of the most consistent midfield performers. Never repeated his 2019 glory but never embarrassed himself either.` },
  { emoji: '👋', owner: 'Hamza & Sangram', title: 'The Departed',               color: '#64748b', body: `Both exited before 2022. Hamza went 2-12 in his final 2021 season. Sangram lasted only 2019. The league's OGs who couldn't hack it long-term. Rumor has it they're still crying about their exits.` },
  { emoji: '📊', owner: 'Teja',            title: 'Mr. Median',                 color: '#3b82f6', body: `7 seasons, 0 championships, 1x toilet bowl loser (2021). The platonic ideal of mediocrity. His win% never strays far from 50%, except when he's actively losing. -$410 all-time. Teja is a living null hypothesis.` },
  { emoji: '⚡', owner: 'Eric',            title: 'The Late Bloomer',           color: '#14b8a6', body: `Missed 2019, quietly improved each year. Best finish was 3rd in 2023 with a +$0 earnings year (somehow broke even on shame). Building toward a championship run — or maybe not.` },
]
