// ─── Trash Talk Narratives ────────────────────────────────────────────────────
export const TRASH_TALK = [
  { emoji: '👑', owner: 'Daniyaal',        title: 'The Fading Empire',          color: '#8b5cf6', body: `The greatest season in league history belongs to Daniyaal — and he'll remind you of it every single week. 13-3 in 2023, 132.6 pts average, two total championships — genuinely dominant at his peak. But since 2023? -$225 in the last two seasons. The empire is still standing, just quietly losing to people he used to blow out. Two trophies and a subscription fee.` },
  { emoji: '🚽', owner: 'Nathan',          title: 'The Human Buy-In',           color: '#06b6d4', body: `7 seasons. 2 toilet bowl trophies. Net earnings: +$5. Not $5 a year — $5 total. Less than a McDouble. Nathan Biyani was runner-up in 2019 and has been professionally irrelevant ever since, reliably finishing somewhere between "bad" and "historically bad." The league has a permanent award for last place. It used to be called the toilet bowl. Now it's basically called the Biyani.` },
  { emoji: '🤝', owner: 'Armaan',          title: 'The Co-Dependent Champion',  color: '#f59e0b', body: `+$350 all-time, multiple playoff runs, positive earnings almost every year — Armaan has done everything right. Except win alone. His only championship came with a co-signer. Shared the 2022 trophy with Dustin, then watched Dustin implode while he kept cashing checks. Credit where it's due: he's the most financially successful manager in this league. Still hasn't stood on that podium by himself though.` },
  { emoji: '📉', owner: 'Dustin',          title: 'The Cautionary Tale',        color: '#a78bfa', body: `Shared a championship in 2022 and has been on a glide path to the basement ever since. -$190 all-time, 2024 toilet bowl loser, -$125 in 2025. Dustin is proof that co-owning a title doesn't confer the skills to defend it. The buy-ins doubled, the stakes got higher, and Dustin got progressively worse — a masterpiece of bad timing. Whatever Armaan has, it is not contagious.` },
  { emoji: '🎰', owner: 'Manu',            title: 'Peaked in 2021',             color: '#ec4899', body: `Went 2-10 in his debut year and posted the lowest single-game score in league history. Then somehow won the whole thing in 2021 — the most chaotic villain arc this league has ever produced. Unfortunately, that was 4 years ago. Since the championship: -$350 in four consecutive losing seasons. Manu has the energy of someone who peaked in high school but won't stop bringing up the game-winning shot.` },
  { emoji: '💸', owner: 'Kerry',           title: 'The Expensive Champion',     color: '#d946ef', body: `The 2025 champion who was the 2023 toilet bowl loser. Paid $225 in losses over 4 years before finally breaking through for the biggest single-season payout in league history ($675). No one's allowed to take that away from him — and no one's going to. But let the record show that he went dead last before he went first. The redemption arc cost more than most people's rent.` },
  { emoji: '🌪️', owner: 'Sonu',            title: 'The Chaos King',             color: '#ef4444', body: `Held the league's highest single-game score ever — until Dustin took that too. Won the 2024 championship (+$600). Then immediately became the 2025 toilet bowl loser (-$125). A $725 net swing across two seasons. Sonu doesn't do anything at half-speed — highest highs, lowest lows, peak chaos. No one in this league has ever climbed higher and fallen faster. At least it's never boring.` },
  { emoji: '🌅', owner: 'Raghav',          title: '2019 Was a Long Time Ago',   color: '#22c55e', body: `Won the very first championship and has been living off that reputation ever since. +$160 in 2019, then -$420 in the next six seasons combined. -$260 all-time. Raghav peaked before the buy-in was even real money, and before the league had real competition. He only won on the backs of the Departed. Silent threat? More like silent landlord who hasn't fixed anything since the first year.` },
  { emoji: '👋', owner: 'Hamza & Sangram', title: 'The Departed',               color: '#64748b', body: `Both bailed before the league got expensive. Sangram lasted one year (2019), finished last, left. Hamza went 2-12 in his final 2021 season and quietly stopped showing up. Classic move — leave before the buy-in hits $50. Whether that was strategy or self-awareness is up for debate.` },
  { emoji: '📊', owner: 'Teja',            title: 'Exhibit A',                  color: '#3b82f6', body: `7 seasons. 0 championships. 1 toilet bowl. A career win percentage that rounds to "fine, I guess." -$410 all-time — the worst net earnings in league history. Teja is statistically indistinguishable from a coin flip. He shows up every year, finishes somewhere in the middle, and donates another buy-in to someone more deserving. The platonic ideal of mediocrity. If the null hypothesis played fantasy football, it would have a better record.` },
  { emoji: '⚡', owner: 'Eric',            title: 'The Sunk Cost',              color: '#14b8a6', body: `6 seasons. -$345 all-time. Career highlight: 2023, where he broke even at exactly $0. Eric has never, in any single season, made a net profit. Not once. He missed 2019 (the year the buy-in was $20) and entered when it mattered more — and has nothing to show for it. At some point this stops being a hobby and starts being a recurring financial mistake. Third place in 2023 though, which was genuinely impressive.` },
]
